title: Home of Chris Adams
email: chris@cadams.com
description: >-
  Sydney based, AI-focused <a href="https://linkedin.com/in/cadamsdotcom" target="_blank" rel="noopener">software entrepreneur</a> who lived in San Francisco & Silicon Valley for 7 years.<br/><br/>
  Motivated by the power of technology to improve lives.<br/><br/>
  20+ years of software engineering experience across full-stack, backend, infrastructure, Site Reliability Enigneering, and AI engineering. Past work includes Uber, Airbnb, Canva, and a wide variety of startups - several of which I co-founded.<br/><br/>
  My hobbies include software engineering, ocean swimming, surf lifesaving, and triathlon - sometimes all at once!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://cadams.com" # the base hostname & protocol for your site, e.g. http://example.com
cover: assets/images/2022/05/mudassir-ali-wpKKwPLRphA-unsplash.jpg
twitter: cadamsdotcom
github:  cadamsdotcom
linkedin: cadamsdotcom
facebook: cadamsdotcom

feed_layout: "Classic"
color_scheme: "Auto"
language: 'en-uk'
navigation_layout: "Logo on cover"

# gems and other configs
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

feed:
  path: feed.xml

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  authors:
    output: true
  tags:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: author
      current: author
      cover: false
      class: 'author-template'
      label: Author
  - scope:
      path: ""
      type: "tags"
    values:
      layout: tag
      current: tag
      cover: false
      class: 'tag-template'
      label: Tag